name: i2p

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  schedule:
    - cron: "5 1 1 * *"
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: i2p
          tags: latest
