name: i2p

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  schedule:
    - cron: "5 1 1 * *"
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test1

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin

    - name: Push the latest Docker image
      run: docker push i2p
